import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..', '..');
const SRC = join(__dirname, '..', 'src');

// Contracts to extract ABIs from
const ABI_TARGETS = [
  { source: 'IDojangScroll.sol/IDojangScroll.json', name: 'dojangScrollAbi' },
  { source: 'IAttestationIndexer.sol/IAttestationIndexer.json', name: 'attestationIndexerAbi' },
  { source: 'SchemaBook.sol/SchemaBook.json', name: 'schemaBookAbi' },
  { source: 'DojangAttesterBook.sol/DojangAttesterBook.json', name: 'dojangAttesterBookAbi' },
];

// Predeploy addresses (OP Stack standard)
const PREDEPLOYS = {
  SchemaRegistry: '0x4200000000000000000000000000000000000020',
  EAS: '0x4200000000000000000000000000000000000021',
};

// --- Generate abi.ts ---

const abiExports = [];

for (const { source, name } of ABI_TARGETS) {
  const artifactPath = join(ROOT, 'out', source);
  const artifact = JSON.parse(readFileSync(artifactPath, 'utf-8'));
  const abi = JSON.stringify(artifact.abi, null, 2);
  abiExports.push(`export const ${name} = ${abi} as const;`);
}

const abiContent = [
  '// This file is auto-generated by scripts/generate.mjs',
  '// Do not edit manually',
  '',
  ...abiExports,
  '',
].join('\n');

writeFileSync(join(SRC, 'abi.ts'), abiContent);
console.log('Generated src/abi.ts');

// --- Generate addresses.ts ---

const deploymentsDir = join(ROOT, 'deployments');
const deploymentFiles = [
  { file: '91342-deploy.json', chainId: 91342 },
];

const chains = {};

for (const { file, chainId } of deploymentFiles) {
  const deployments = JSON.parse(readFileSync(join(deploymentsDir, file), 'utf-8'));
  chains[chainId] = {
    ...deployments,
    ...PREDEPLOYS,
  };
}

const addressesContent = [
  '// This file is auto-generated by scripts/generate.mjs',
  '// Do not edit manually',
  '',
  `export const addresses = ${JSON.stringify(chains, null, 2)} as const;`,
  '',
].join('\n');

writeFileSync(join(SRC, 'addresses.ts'), addressesContent);
console.log('Generated src/addresses.ts');
